function(_stim_cas_pch directory)
  get_property(targets DIRECTORY "${directory}" PROPERTY BUILDSYSTEM_TARGETS)
  foreach(target IN LISTS targets)
    get_target_property(headers "${target}" PRECOMPILE_HEADERS)
    if(NOT headers)
      continue()
    endif()
    set(portable)
    foreach(header IN LISTS headers)
      set(mapped "${header}")
      if(IS_ABSOLUTE "${header}")
        foreach(root IN ITEMS "${CMAKE_BINARY_DIR}" "$ENV{STIM_ANDROID_CAS_SOURCE_ROOT}")
          string(FIND "${header}" "${root}/" position)
          if(position EQUAL 0)
            string(LENGTH "${root}/" length)
            string(SUBSTRING "${header}" ${length} -1 suffix)
            if(root STREQUAL CMAKE_BINARY_DIR)
              set(mapped "\"/^build/${suffix}\"")
            else()
              set(mapped "\"/^src/${suffix}\"")
            endif()
            break()
          endif()
        endforeach()
      endif()
      list(APPEND portable "${mapped}")
    endforeach()
    set_property(TARGET "${target}" PROPERTY PRECOMPILE_HEADERS "${portable}")
  endforeach()
  get_property(children DIRECTORY "${directory}" PROPERTY SUBDIRECTORIES)
  foreach(child IN LISTS children)
    _stim_cas_pch("${child}")
  endforeach()
endfunction()
cmake_language(DEFER CALL _stim_cas_pch "${CMAKE_CURRENT_SOURCE_DIR}")
