if(NOT ANDROID OR CMAKE_VERSION VERSION_LESS 3.22
   OR NOT CMAKE_CXX_COMPILER_ID STREQUAL "Clang"
   OR CMAKE_CXX_COMPILER_VERSION VERSION_LESS 18
   OR NOT CMAKE_CXX_COMPILER_VERSION VERSION_LESS 19
   OR NOT STIM_PCH_ROOT OR NOT STIM_PCH_CCACHE
   OR NOT STIM_PCH_IDENTITY OR NOT STIM_PCH_NODE OR NOT STIM_PCH_COMPILER OR NOT STIM_PCH_HEADERS)
  return()
endif()
include_guard(DIRECTORY)

function(stim_pch_targets directory output)
  get_property(targets DIRECTORY "${directory}" PROPERTY BUILDSYSTEM_TARGETS)
  get_property(children DIRECTORY "${directory}" PROPERTY SUBDIRECTORIES)
  foreach(child IN LISTS children)
    stim_pch_targets("${child}" nested)
    list(APPEND targets ${nested})
  endforeach()
  set(${output} "${targets}" PARENT_SCOPE)
endfunction()

function(stim_pch_relocate)
  file(REAL_PATH "${STIM_PCH_ROOT}" root)
  stim_pch_targets("${CMAKE_CURRENT_SOURCE_DIR}" targets)
  foreach(owner IN LISTS targets)
    get_target_property(headers "${owner}" PRECOMPILE_HEADERS)
    if(NOT headers)
      continue()
    endif()
    set(family "${owner}")
    foreach(target IN LISTS targets)
      get_target_property(reuse "${target}" PRECOMPILE_HEADERS_REUSE_FROM)
      if(reuse STREQUAL owner)
        list(APPEND family "${target}")
      endif()
    endforeach()
    set(eligible TRUE)
    foreach(target IN LISTS family)
      get_target_property(launcher "${target}" CXX_COMPILER_LAUNCHER)
      get_target_property(disabled "${target}" DISABLE_PRECOMPILE_HEADERS)
      get_target_property(source "${target}" SOURCE_DIR)
      file(REAL_PATH "${source}" source)
      cmake_path(IS_PREFIX root "${source}" NORMALIZE contained)
      if(NOT launcher STREQUAL STIM_PCH_CCACHE OR disabled OR NOT contained)
        set(eligible FALSE)
      endif()
    endforeach()
    set(relocated)
    foreach(header IN LISTS headers)
      if(header MATCHES "\\$<")
        set(eligible FALSE)
      elseif(IS_ABSOLUTE "${header}")
        file(REAL_PATH "${header}" absolute)
        cmake_path(IS_PREFIX root "${absolute}" NORMALIZE contained)
        if(NOT contained)
          set(eligible FALSE)
        endif()
        file(RELATIVE_PATH relative "${root}" "${absolute}")
        list(APPEND relocated "<${relative}>")
      elseif(header MATCHES "^[<\"]")
        list(APPEND relocated "${header}")
      else()
        set(eligible FALSE)
      endif()
    endforeach()
    if(NOT eligible)
      continue()
    endif()
    set_property(TARGET "${owner}" PROPERTY PRECOMPILE_HEADERS "${relocated}")
    foreach(target IN LISTS family)
      file(RELATIVE_PATH relative_root "${CMAKE_BINARY_DIR}" "${root}")
      if(NOT relative_root)
        set(relative_root ".")
      endif()
      target_compile_options("${target}" PRIVATE
        "SHELL:-Xclang -relocatable-pch"
        "SHELL:-Xclang -fno-pch-timestamp"
        "SHELL:-Xclang -isysroot -Xclang \"${relative_root}\""
        "-DSTIM_PCH_CACHE_ID=${STIM_PCH_IDENTITY}")
      # Clang's PCH preprocessor opens the serialized source relative to an include directory.
      target_include_directories("${target}" PRIVATE "${root}")
      set_property(TARGET "${target}" PROPERTY CXX_COMPILER_LAUNCHER
        "${STIM_PCH_NODE};${STIM_PCH_COMPILER};--cache;${STIM_PCH_HEADERS};${STIM_PCH_CCACHE}")
    endforeach()
    message(STATUS "Stim: relocatable PCH for ${owner}")
  endforeach()
endfunction()

cmake_language(DEFER CALL stim_pch_relocate)
