import type { Method, StatusPayload } from '@stim-cli/core/phone-protocol';

const receivedAt = '2026-09-27T12:00:00Z';
const activity = { state: 'active', basis: [] };
const app = { id: 'app', state: 'running' };
const miss = {
  kind: 'changed',
  summary: 'Native files changed',
  changeCount: 1,
  changes: [{ source: 'app.json', change: 'changed', category: 'app-config' }],
  baseline: { fingerprint: 'abc', from: 'workspace' },
  rekeyedBy: [],
};
const last = {
  platform: 'ios',
  status: 'ok',
  cacheHit: 'local',
  cacheSkipped: false,
  durationMs: 1000,
  fingerprint: 'abc',
  startedAt: receivedAt,
  finishedAt: receivedAt,
  missReason: miss,
};

export function receiveStatus(captured: StatusPayload): StatusPayload {
  return {
    ...captured,
    machine: {
      memorySource: 'footprint',
      owners: [
        {
          kind: 'metro',
          name: 'Metro',
          workspace: '/app',
          id: '8081',
          owned: true,
          cpuPercent: 10,
          residentMb: 128,
          memoryMb: 100,
          processes: 1,
        },
      ],
    },
    environments: [
      {
        ...captured.environments[0]!,
        path: '/app',
        live: true,
        phase: 'live',
        warmStep: 'refresh',
        memorySource: 'footprint',
        stage: {
          kind: 'running',
          since: receivedAt,
          platform: 'ios',
          closedApps: [{ platform: 'ios', slot: 'default' }],
        },
        ios: { udid: 'SIM', name: 'iPhone', owned: true, state: 'Booted', activity, app, appPresence: 'closed' },
        android: {
          name: 'Emulator',
          owned: true,
          physical: false,
          state: 'detected',
          activity,
          app,
          appPresence: 'closed',
        },
        web: {
          browser: 'chrome',
          version: null,
          running: true,
          pid: 1,
          supervisorPid: 2,
          url: 'https://app',
          headless: false,
          viewport: 'desktop',
          profile: '/profile',
          cdpEndpoint: null,
          page: { url: 'https://app', state: 'loaded' },
          activity,
        },
        macos: {
          launchId: 'm',
          arguments: [],
          product: 'App',
          bundle: '/App.app',
          bundleId: 'app',
          executable: '/App',
          state: 'running',
          hostLaunched: true,
          host: {
            machine: 'mini',
            session: 'host',
            appSlot: 1,
            appAttempt: 'attempt',
            bundleId: 'app.hosted1',
            agent: { driver: 'none', setting: 'hosting.agentDriver' },
          },
          build: { state: 'ok', startedAt: receivedAt },
        },
        metro: {
          port: 8081,
          running: true,
          pid: 1,
          tunnel: { provider: 'ngrok', url: 'https://tunnel' },
          idleStop: { reason: 'idle', at: receivedAt, idleMinutes: 10 },
          bundle: {
            bundling: false,
            platform: 'ios',
            last: { platform: 'ios', status: 'ok', durationMs: 1000, finishedAt: receivedAt },
          },
        },
        issues: [
          {
            code: 'avd-missing',
            severity: 'warning',
            message: 'Device missing',
            remedy: 'stim android',
            workspace: '/app',
          },
        ],
        build: {
          platform: 'ios',
          slot: 'default',
          state: 'running',
          phase: 'compile',
          startedAt: receivedAt,
          phaseStartedAt: receivedAt,
          outcome: 'cold',
          outcomeKnown: true,
          cacheLookupOutcome: 'miss',
          expectedMs: null,
          expectedPhaseMs: null,
          basis: 0,
          plannedPhases: [{ phase: 'compile', expectedMs: 1000 }],
          missReason: miss,
          placement: 'local',
          missProvisional: true,
          detail: { step: 'compile', unit: 'targets', done: 1, total: 2, line: 'Compiling App', updatedAt: receivedAt },
        },
        lastBuilds: { ios: last },
        builds: {
          ios: [
            {
              ...last,
              result: 'succeeded',
              slot: 'default',
              configuration: 'Debug',
              cacheKey: 'abc',
              phases: { compile: 1000 },
            },
          ],
        },
        worktree: {
          path: '/app',
          git: { changed: 1, untracked: 0, upstream: 'origin/main', ahead: 0, behind: 0, mergedInto: null },
          pullRequest: {
            number: 1,
            url: 'https://pr',
            title: 'Change',
            state: 'open',
            checks: null,
            reviewDecision: 'approved',
            checkedAt: receivedAt,
          },
          gitChip: { parts: [{ kind: 'changed', count: 1 }], ci: 'passing' },
        },
        agents: [{ tool: 'codex', sessionId: 'agent', cwd: '/app' }],
        endedAgents: [{ tool: 'codex', sessionId: 'ended', cwd: '/app', endedAt: receivedAt }],
        remoteDevices: [
          {
            platform: 'ios',
            backend: 'eas',
            sessionId: 'remote',
            state: 'claimed',
            startedAt: receivedAt,
            webPreviewUrl: null,
          },
        ],
        physicalDevices: [
          {
            platform: 'ios',
            slot: 'phone',
            id: 'PHONE',
            name: 'Phone',
            model: 'iPhone',
            owned: false,
            physical: true,
            connection: 'connected',
            lease: { holder: '/app', kind: 'run', grantedAt: receivedAt, expiresAt: receivedAt },
          },
        ],
      },
    ],
  };
}

export const statusEnumPaths: string[] = [
  'machine.memorySource',
  'machine.owners.0.kind',
  ...[
    'phase',
    'warmStep',
    'memorySource',
    'stage.kind',
    'stage.platform',
    'stage.closedApps.0.platform',
    'ios.activity.state',
    'ios.app.state',
    'ios.appPresence',
    'android.state',
    'android.activity.state',
    'android.app.state',
    'android.appPresence',
    'web.browser',
    'web.viewport',
    'web.page.state',
    'web.activity.state',
    'macos.state',
    'macos.build.state',
    'macos.hostLaunched',
    'macos.host.agent.setting',
    'metro.tunnel.provider',
    'metro.idleStop.reason',
    'metro.bundle.platform',
    'metro.bundle.last.platform',
    'metro.bundle.last.status',
    'issues.0.severity',
    'build.platform',
    'build.state',
    'build.phase',
    'build.outcome',
    'build.cacheLookupOutcome',
    'build.plannedPhases.0.phase',
    'build.detail.step',
    'build.detail.unit',
    'build.missReason.kind',
    'build.missReason.changes.0.change',
    'build.missReason.changes.0.category',
    'build.missReason.baseline.from',
    'lastBuilds.ios.platform',
    'lastBuilds.ios.status',
    'lastBuilds.ios.cacheHit',
    'builds.ios.0.platform',
    'builds.ios.0.status',
    'builds.ios.0.cacheHit',
    'builds.ios.0.result',
    'worktree.pullRequest.state',
    'worktree.pullRequest.reviewDecision',
    'worktree.gitChip.ci',
    'agents.0.tool',
    'endedAgents.0.tool',
    'remoteDevices.0.platform',
    'remoteDevices.0.backend',
    'remoteDevices.0.state',
    'physicalDevices.0.platform',
    'physicalDevices.0.connection',
    'physicalDevices.0.lease.kind',
  ].map((path) => `environments.0.${path}`),
];

export function replaceReceivedField<T>(fixture: T, path: string, value: unknown): T {
  const copy = JSON.parse(JSON.stringify(fixture));
  const keys = path.split('.');
  let target = copy;
  for (const key of keys.slice(0, -1)) target = target[key];
  target[keys.at(-1)!] = value;
  return copy;
}

const notification = {
  seq: 1,
  at: receivedAt,
  id: 'n',
  category: 'started',
  title: 'Work started',
  body: 'App',
  quiet: false,
  suppressed: 'muted',
  target: { kind: 'device', path: '/app', platform: 'ios', slot: 'default' },
};
const plan = {
  platform: 'ios',
  fingerprint: 'abc',
  cacheKey: 'abc',
  cacheHit: false,
  provider: null,
  cacheSkipped: false,
  prebuild: 'none',
  outcome: 'cold',
  expectedMs: null,
  basis: 0,
  missReason: miss,
};
export const resultEnumCases: [Method, unknown, string, unknown][] = [
  [
    'hello',
    {
      protocol: 1,
      server: { name: 'Mac', version: '1', stim: '1' },
      capabilities: ['read'],
      approval: { state: 'pending', expiresAt: receivedAt },
    },
    'approval.state',
    'future-kind',
  ],
  [
    'machine.get',
    {
      volumes: [],
      memory: { totalBytes: 1024, usedBytes: 100, pressure: 'normal' },
      load: { avg1: 0, avg5: 0, avg15: 0, cpus: 4 },
      sampledAt: receivedAt,
    },
    'memory.pressure',
    'future-kind',
  ],
  [
    'machine.history',
    { intervalMs: 1000, samples: [{ at: 1, cpu: 0.1, memoryUsedBytes: 100, memoryPressure: 0, diskFreeBytes: 100 }] },
    'samples.0.memoryPressure',
    99,
  ],
  ...['section', 'kind'].map((path): [Method, unknown, string, unknown] => [
    'workspace.diff',
    { path: 'app.ts', patches: [{ section: 'staged', kind: 'text', text: '+App' }] },
    `patches.0.${path}`,
    'future-kind',
  ]),
  ['frames.subscribe', { subscription: 's', video: 'h264' }, 'video', 'future-kind'],
  [
    'replay.range',
    {
      enabled: true,
      recording: true,
      spans: [{ start: 1, end: 2 }],
      markers: [{ at: 1, kind: 'action', label: 'Tap' }],
    },
    'markers.0.kind',
    'future-kind',
  ],
  [
    'replay.keyframe',
    { start: 1, end: 2, at: 1, width: 400, height: 800, posture: 'folded', data: 'video' },
    'posture',
    'future-kind',
  ],
  ...[
    'platform',
    'cacheHit',
    'prebuild',
    'outcome',
    'missReason.kind',
    'missReason.changes.0.change',
    'missReason.changes.0.category',
    'missReason.baseline.from',
  ].map((path): [Method, unknown, string, unknown] => ['build.plan', plan, path, 'future-kind']),
  ['action', { action: 'reload', workspace: '/app', output: {} }, 'action', 'future-kind'],
  ['control.begin', { session: 'c', platform: 'ios', lease: null, postures: ['folded'] }, 'platform', 'future-kind'],
  ['control.begin', { session: 'c', platform: 'ios', lease: null, postures: ['folded'] }, 'postures.0', 'future-kind'],
  ...['category', 'suppressed', 'target.platform'].map((path): [Method, unknown, string, unknown] => [
    'notifications.list',
    { log: 'l', cursor: 1, notifications: [notification] },
    `notifications.0.${path}`,
    'future-kind',
  ]),
  [
    'notifications.list',
    {
      log: 'l',
      cursor: 1,
      notifications: [{ ...notification, target: { kind: 'build', path: '/app', platform: 'ios' } }],
    },
    'notifications.0.target.platform',
    'future-kind',
  ],
];

export const eventEnumCases: [unknown, string][] = [
  ...['platform', 'posture', 'mime'].map((path): [unknown, string] => [
    {
      event: 'frame',
      subscription: 's',
      platform: 'ios',
      slot: 'default',
      mime: 'image/jpeg',
      width: 400,
      height: 800,
      capturedAt: receivedAt,
      data: 'image',
      posture: 'folded',
    },
    path,
  ]),
  [{ event: 'control-ended', session: 'c', reason: 'idle', message: 'Control ended' }, 'reason'],
  ...['category', 'suppressed', 'target.platform'].map((path): [unknown, string] => [
    { event: 'notification', log: 'l', notification },
    `notification.${path}`,
  ]),
];
