import Foundation

/// What the Mac pasteboard holds, reduced to what the sync rules need.
public struct PasteboardSnapshot: Equatable, Sendable {
  public var changeCount: Int
  public var types: [String]
  public var text: String?

  public init(changeCount: Int, types: [String], text: String?) {
    self.changeCount = changeCount
    self.types = types
    self.text = text
  }
}

/// Decides when the Mac clipboard and a viewed device's clipboard are copied to each other, and what is never copied.
/// It performs no I/O: the viewer reads and writes the pasteboards and reports what happened.
public struct ClipboardSync: Equatable, Sendable {
  public enum WindowState: Equatable, Sendable {
    case key
    case visible
    case hidden
  }

  public enum Activity: Equatable, Sendable {
    /// Copy both ways while the viewer window is key.
    case sync
    /// Read the device once more as the viewer window stops being key.
    case flush
    case none
  }

  /// Text larger than this is never copied, in either direction.
  public static let maxTextBytes = 256 * 1024

  public static let concealedType = "org.nspasteboard.ConcealedType"
  public static let transientType = "org.nspasteboard.TransientType"
  static let skippedTypes: Set<String> = [
    concealedType, transientType, "org.nspasteboard.AutoGeneratedType", "com.agilebits.onepassword",
    "de.petermaurer.TransientPasteboardType", "com.typeit4me.clipping", "Pasteboard generator type",
  ]
  static let textType = "public.utf8-plain-text"
  static let nonTextTypes: Set<String> = [
    "public.file-url", "public.png", "public.tiff", "public.jpeg", "public.heic", "com.compuserve.gif", "com.adobe.pdf",
  ]

  /// The text of a Mac pasteboard item that may go to a device, or nil for concealed or transient items (the marks
  /// password managers and one-time-code apps set), items carrying files or images, and empty or oversized text.
  public static func macText(_ snapshot: PasteboardSnapshot) -> String? {
    let types = Set(snapshot.types)
    guard types.contains(textType), types.isDisjoint(with: skippedTypes),
      types.isDisjoint(with: nonTextTypes)
    else { return nil }
    return deviceText(snapshot.text)
  }

  /// A device clipboard's text if it may go to the Mac: non-empty and not oversized.
  public static func deviceText(_ text: String?) -> String? {
    guard let text, !text.isEmpty, text.utf8.count <= maxTextBytes else { return nil }
    return text
  }

  /// Sync runs only for a viewer the user turned it on for, on a device Desktop controls, and only while the window
  /// is key. A window that just stopped being key but is still visible gets one last read of the device.
  public static func activity(enabled: Bool, hasTarget: Bool, window: WindowState) -> Activity {
    guard enabled, hasTarget else { return .none }
    switch window {
    case .key: return .sync
    case .visible: return .flush
    case .hidden: return .none
    }
  }

  /// The text both clipboards held after the last copy.
  public private(set) var synced: String?
  public private(set) var macChangeCount: Int?
  private var baselined = false

  public init() {}

  /// The text to copy to the device now (a Mac item that is skipped makes the next device read a fresh baseline, so
  /// it never replaces that item): the Mac pasteboard changed since it was last looked at, or the viewer just
  /// became key, and its eligible text is not what both sides already hold.
  public mutating func textForDevice(_ snapshot: PasteboardSnapshot, becameKey: Bool) -> String? {
    guard becameKey || snapshot.changeCount != macChangeCount else { return nil }
    macChangeCount = snapshot.changeCount
    guard let text = Self.macText(snapshot) else {
      baselined = false
      return nil
    }
    guard text != synced else { return nil }
    return text
  }

  public mutating func didCopyToDevice(_ text: String) {
    synced = text
    baselined = true
  }

  /// The text to copy to the Mac now: the device clipboard differs from what both sides held. `deviceText` is nil
  /// when the read failed. The first successful read of a session only records the device's text, so opening a
  /// viewer never replaces the Mac clipboard.
  public mutating func textForMac(deviceText raw: String?) -> String? {
    guard let raw else { return nil }
    let text = Self.deviceText(raw)
    guard baselined else {
      synced = text
      baselined = true
      return nil
    }
    guard let text, text != synced else { return nil }
    return text
  }

  public mutating func didCopyToMac(_ text: String, changeCount: Int) {
    synced = text
    macChangeCount = changeCount
  }
}
