// Generated by apps/desktop/scripts/generate-tokens.mjs from packages/stim-cli/src/guide/tutorial-data.ts. Do not edit.
// swift-format-ignore-file

public struct TutorialStep: Sendable {
  public let id: String
  public let title: String
  public let who: String
  public let optional: Bool
  public let ask: String?
  public let section: String?
  public let commands: [String]
}

public enum TutorialSteps {
  public static let supportedVersions: Set<Int> = [2]
  public static let restartPrompt = "Restart the Stim tutorial."
  public static let retryAsk = "The first iOS build of the tutorial app in {base} failed. Find out why and run it on iOS again."
  public static let all: [TutorialStep] = [
    TutorialStep(
      id: "begin", title: "Get the Test App", who: "agent", optional: false,
      ask: "Clone appandflow/stim-tutorial into {base} and install its dependencies. Use a fresh folder: if {base} already exists or is inside another git repository, stop and ask me for another folder, and never git add in my own repo. Follow stim guide tutorial run.", section: "run",
      commands: [

      ]),
    TutorialStep(
      id: "build", title: "Make a Change", who: "you", optional: false,
      ask: nil, section: nil,
      commands: [

      ]),
    TutorialStep(
      id: "parallel", title: "Change It Again in Parallel", who: "you", optional: false,
      ask: nil, section: nil,
      commands: [

      ]),
    TutorialStep(
      id: "device", title: "Live View and Control", who: "you", optional: true,
      ask: nil, section: nil,
      commands: [
        "stim status"
      ]),
    TutorialStep(
      id: "agent", title: "Agent Actions and Replay", who: "agent", optional: true,
      ask: "Open the app on the iOS simulator, take a screenshot and confirm the title color.", section: nil,
      commands: [
        "cd \"{tour}\"",
        "export AGENT_DEVICE_STATE_DIR=\"{stateDir}\"",
        "agent-device open dev.stim.tutorial --platform ios --udid {udid}",
        "agent-device screenshot tutorial.png",
        "agent-device close",
        "stim logs --source agent --tail 10",
      ]),
    TutorialStep(
      id: "logs", title: "App Logs", who: "you", optional: true,
      ask: nil, section: nil,
      commands: [
        "stim logs --errors",
        "stim logs --grep stim:tutorial",
      ]),
    TutorialStep(
      id: "phone", title: "Watch on Your Phone", who: "you", optional: true,
      ask: nil, section: nil,
      commands: [

      ]),
    TutorialStep(
      id: "machine", title: "Build on Another Mac", who: "both", optional: true,
      ask: "Build the app for iOS on {machine} with stim instead of on this Mac. Do not approve or pair anything.", section: nil,
      commands: [
        "cd \"{tour}\"",
        "stim ios --remote-build \"{machine}\" --no-build-cache",
      ]),
    TutorialStep(
      id: "share", title: "Share Your Finish", who: "you", optional: true,
      ask: "Open a pull request to appandflow/stim-tutorial with my title color change, and include a screenshot of it running in the simulator. See stim guide tutorial share.", section: "share",
      commands: [
        "cd \"{tour}\"",
        "xcrun simctl io {udid} screenshot finish.png",
        "gh repo fork appandflow/stim-tutorial --remote --remote-name fork",
        "git push -u fork HEAD",
        "gh pr create --repo appandflow/stim-tutorial --attach \"finish.png#The change running in the simulator\"",
      ]),
    TutorialStep(
      id: "finish", title: "Finish and Archive", who: "agent", optional: false,
      ask: "I'm done with these experiments in {base} and don't need the changes. Stop the apps and remove the worktrees {worktrees}, and keep the clone. Follow stim guide tutorial finish.", section: "finish",
      commands: [
        "cd \"{tour}\"",
        "stim stop",
        "cd \"{second}\"",
        "stim stop",
        "cd \"{base}\"",
        "stim worktree remove \"{tour}\"",
        "stim worktree remove \"{second}\"",
      ]),
  ]
}
