import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join, relative } from 'node:path';
import { fileURLToPath } from 'node:url';

const desktop = join(dirname(fileURLToPath(import.meta.url)), '..');
const source = join(desktop, '../mobile/src/design/tokens.ts');
const output = join(desktop, 'Sources/StimDesktop/Design/Tokens.swift');
// Node warns that apps/mobile/package.json declares no module type, then loads the ES module anyway.
process.removeAllListeners('warning');
process.on('warning', (warning) => {
  if (warning.code !== 'MODULE_TYPELESS_PACKAGE_JSON') console.warn(warning);
});
const tokens = await import(source);

const weights = { regular: '.regular', medium: '.medium', semibold: '.semibold', bold: '.bold' };

function rgba(value) {
  const hex = /^#([0-9a-f]{6})$/i.exec(value);
  if (hex) return `0x${hex[1].toUpperCase()}FF`;
  const fn = /^rgba\((\d+),\s*(\d+),\s*(\d+),\s*([\d.]+)\)$/.exec(value);
  if (!fn) throw new Error(`Unsupported color ${value}`);
  const [r, g, b] = fn.slice(1, 4).map((c) => Number(c).toString(16).padStart(2, '0'));
  const a = Math.round(Number(fn[4]) * 255)
    .toString(16)
    .padStart(2, '0');
  return `0x${(r + g + b + a).toUpperCase()}`;
}

function constants(name, values) {
  const lines = Object.entries(values).map(([key, value]) => `  static let ${key}: CGFloat = ${value}`);
  return `enum ${name} {\n${lines.join('\n')}\n}`;
}

function textStyles(text, macos) {
  const names = Object.keys(text);
  const style = (name) => ({ ...text[name], ...macos[name] });
  const cases = (field, format) => names.map((name) => `    case .${name}: ${format(style(name)[field])}`).join('\n');
  return [
    'enum TextVariant: CaseIterable {',
    `  case ${names.join(', ')}`,
    '',
    '  var size: CGFloat {',
    '    switch self {',
    cases('fontSize', String),
    '    }',
    '  }',
    '',
    '  var lineHeight: CGFloat {',
    '    switch self {',
    cases('lineHeight', String),
    '    }',
    '  }',
    '',
    '  var weight: Font.Weight {',
    '    switch self {',
    cases('fontWeight', (w) => weights[w]),
    '    }',
    '  }',
    '}',
  ].join('\n');
}

function palette(colors) {
  const lines = Object.keys(colors.light).map(
    (key) => `  static let ${key} = Color(light: ${rgba(colors.light[key])}, dark: ${rgba(colors.dark[key])})`,
  );
  const all = Object.keys(colors.light).map((key) => `("${key}", ${key})`);
  return `enum Palette {\n${lines.join('\n')}\n\n  static let all: [(name: String, color: Color)] = [\n    ${all.join(',\n    ')},\n  ]\n}`;
}

function media(values) {
  const lines = Object.entries(values).map(([key, value]) => `  static let ${key} = Color(rgba: ${rgba(value)})`);
  return `enum Media {\n${lines.join('\n')}\n}`;
}

const swift = `// Generated by apps/desktop/scripts/generate-tokens.mjs from ${relative(join(desktop, '../..'), source)}. Do not edit.

import SwiftUI

${constants('Space', tokens.space)}

${constants('Radius', tokens.radius)}

enum Opacity {
${Object.entries(tokens.opacity)
  .map(([key, value]) => `  static let ${key}: Double = ${value}`)
  .join('\n')}
}

${textStyles(tokens.text, tokens.macosText)}

${palette(tokens.colors)}

${media(tokens.media)}

enum FontFamily {
  static let sans = "${tokens.fonts.sans.macos}"
  static let mono = "${tokens.fonts.mono.macos}"
}
`;

if (process.argv.includes('--check')) {
  if (readFileSync(output, 'utf8') !== swift) {
    console.error(
      `${relative(process.cwd(), output)} is out of date. Run: node apps/desktop/scripts/generate-tokens.mjs`,
    );
    process.exit(1);
  }
} else {
  writeFileSync(output, swift);
}
