import chalk from 'chalk';
import type { Command } from 'commander';
import TOPICS from '../guide/index.ts';
import type { GuideSection, GuideTopic } from '../guide/types.ts';

export function topicNames(): string[] {
  return Object.keys(TOPICS);
}

function topicByName(name: string): GuideTopic | null {
  return Object.hasOwn(TOPICS, name) ? (TOPICS[name] ?? null) : null;
}

const LOOKUPS = new Map<string, Record<string, GuideSection>>();

export function sectionLookup(name: string): Record<string, GuideSection> {
  const cached = LOOKUPS.get(name);
  if (cached) return cached;
  const lookup: Record<string, GuideSection> = Object.create(null);
  for (const [sectionName, section] of Object.entries(topicByName(name)?.sections ?? {})) {
    lookup[sectionName] = section;
    for (const alias of section.aliases ?? []) lookup[alias] = section;
  }
  LOOKUPS.set(name, lookup);
  return lookup;
}

export function sectionNames(name: string): string[] {
  return Object.keys(topicByName(name)?.sections ?? {});
}

const COMMAND_NOTATION = 'Commands use `stim`. If it is not installed globally, replace `stim` with `npx stim`.';

function wordCount(text: string): number {
  return text.trim().split(/\s+/).filter(Boolean).length;
}

export function renderSectionIndex(name: string): string | null {
  const topic = topicByName(name);
  if (!topic?.sections) return null;
  const entries = Object.entries(topic.sections);
  const width = Math.max(...entries.map(([sectionName]) => sectionName.length));
  const lines = ['SECTIONS'];
  for (const [sectionName, section] of entries) {
    if (section.separator) {
      lines.push('', section.separator, '');
      if (section.context) lines.push(section.context, '');
    }
    lines.push(`  ${sectionName.padEnd(width)}  ${`${wordCount(section.body())}w`.padStart(6)}  ${section.summary}`);
    for (const alias of section.aliases ?? []) lines.push(`    = ${alias}`);
  }
  lines.push('', `Read one with:  stim guide ${name} ${topic.sectionHint ?? '<section>'}`);
  return lines.join('\n');
}

export function renderTopic(name: string): string | null {
  const topic = topicByName(name);
  if (!topic) return null;
  if (topic.body) return `${COMMAND_NOTATION}\n\n${topic.body()}`;
  return `${COMMAND_NOTATION}\n\n${topic.preamble?.() ?? ''}\n\n${renderSectionIndex(name) ?? ''}`;
}

export function renderSection(name: string, section: string): string | null {
  const lookup = sectionLookup(name);
  const found = Object.hasOwn(lookup, section) ? lookup[section] : undefined;
  if (!found) return null;
  const context = found.context ? `${found.context}\n\n` : '';
  return `${COMMAND_NOTATION}\n\n${context}${found.body()}`;
}

function topicOwning(section: string): string | null {
  for (const name of topicNames()) {
    if (Object.hasOwn(sectionLookup(name), section)) return name;
  }
  return null;
}

export function renderIndex(version: string): string {
  const lines = [
    `stim ${version} -- reference for the binary you are running.`,
    '',
    COMMAND_NOTATION,
    '',
    'This output is generated by the CLI, so it always matches this version.',
    'The bundled skill routes coding agents to the agent topic. Other topics',
    'carry the detailed command contracts and remedies.',
    '',
    'TOPICS',
  ];
  const width = Math.max(...topicNames().map((n) => n.length));
  for (const name of topicNames()) {
    lines.push(`  ${name.padEnd(width)}  ${TOPICS[name]?.summary ?? ''}`);
  }
  lines.push('', 'Read one with:  stim guide <topic>   (sectioned topics: stim guide <topic> <section>)');
  return lines.join('\n');
}

export default function guideCommand(program: Command, version: string): void {
  program
    .command('guide [topic] [section]')
    .description(
      'Print reference documentation for THIS version of Stim (topics: ' +
        topicNames().join(', ') +
        '). A topic with sections prints its section index; name a section to print only it, ' +
        'e.g. `stim guide errors STIM_NO_METRO` or `stim guide lifecycle builds`. ' +
        'Generated by the binary, so it cannot drift from the installed CLI.',
    )
    .action((topic, section) => {
      if (!topic) {
        console.log(renderIndex(version));
        return;
      }
      const body = renderTopic(topic);
      if (!body) {
        console.error(chalk.red(`Unknown topic "${topic}".`));
        console.error(chalk.dim(`Available: ${topicNames().join(', ')}`));
        const owner = topicOwning(topic);
        if (owner) console.error(chalk.dim(`Did you mean: stim guide ${owner} ${topic}`));
        process.exit(1);
      }
      if (!section) {
        console.log(body);
        return;
      }
      const index = renderSectionIndex(topic);
      if (!index) {
        console.error(chalk.red(`Topic "${topic}" has no sections.`));
        process.exit(1);
      }
      const sectionBody = renderSection(topic, section);
      if (!sectionBody) {
        console.error(chalk.red(`Unknown section "${section}" in topic "${topic}".`));
        console.error(index);
        process.exit(1);
      }
      console.log(sectionBody);
    });
}
