// Generated by apps/desktop/scripts/generate-tokens.mjs from apps/mobile/src/lib/agent-prompts.ts. Do not edit.

enum AgentPrompts {
  static let all: [String] = [
    "Run the app on iOS.",
    "Run the app on Android.",
    "Run the app on my connected iPhone.",
    "Run the app on an iOS simulator using an EAS build.",
    "Make this change in a separate worktree and validate it on iOS.",
    "Make this change in a separate worktree and validate it on Android.",
    "Show app errors from the last 10 minutes.",
    "Show iOS build performance.",
  ]
}
