// Generated by apps/desktop/scripts/generate-tokens.mjs from apps/mobile/src/lib/agent-prompts.ts. Do not edit.
// swift-format-ignore-file

enum AgentPrompts {
  static let all: [String] = [
    "Run the app on iOS.",
    "Run the app on Android.",
    "Run the app on my connected iPhone.",
    "Run the app on an iOS simulator using an EAS build.",
    "Make this change in a separate worktree and validate it on iOS.",
    "Make this change in a separate worktree and validate it on Android.",
    "Show app errors from the last 10 minutes.",
    "Show iOS build performance.",
  ]
}

enum TipPrompts {
  static let byTopic: [String: String] = [
    "easProfile": "Run the app on an iOS simulator with an EAS development build. Read eas.json, pick the development profile that builds for the simulator, and run stim ios --eas-profile with it. If no profile fits, ask me.",
    "macos": "Read stim guide macos, set macos.product and macos.infoPlist in .stim.json for this Swift package, and run it as a macOS app with stim macos.",
    "logs": "Show me only the errors from the app, Metro and the build with stim logs --errors.",
  ]
}
