// Generated by apps/desktop/scripts/generate-tokens.mjs from apps/mobile/src/lib/agent-prompts.ts. Do not edit.

enum AgentPrompts {
  static let all: [String] = [
    "Run the app on iOS.",
    "Run the app on Android.",
    "Run the app on my connected iPhone.",
    "Run the app on an iOS simulator using an EAS build.",
    "Make this change in a separate worktree and validate it on iOS.",
    "Make this change in a separate worktree and validate it on Android.",
    "Show app errors from the last 10 minutes.",
    "Show iOS build performance.",
  ]
}

enum TryThisPrompts {
  static let byTip: [String: String] = [
    "easProfile": "Run the app on an iOS simulator with an EAS development build. Read eas.json, pick the development profile that builds for the simulator, and run stim ios --eas-profile with it. If no profile fits, ask me.",
    "easSimulator": "Run the app on an EAS cloud simulator with stim start --remote and then stim ios --remote eas. EAS bills the session, so run stim stop when we are done.",
    "remoteBuild": "Read stim guide settings and tell me what I need to do to build on my other Mac with remote.machines and stim ios --remote-build. Do not change remote settings or approve anything yourself.",
    "hostedSimulator": "Read stim guide lifecycle hosted-ios and tell me what I need to do to run the iOS simulator on my other Mac with stim ios --remote. Do not change remote settings or approve anything yourself.",
    "macos": "Read stim guide macos, set macos.product and macos.infoPlist in .stim.json for this Swift package, and run it as a macOS app with stim macos.",
    "physicalDevice": "Run the app on my connected iPhone with stim ios --device, or on my Android phone with stim android --device.",
    "web": "Start the dev server, open the app in the browser with stim web, and show me the page errors with stim logs --errors.",
    "logs": "Run the app on iOS, then show me only its errors with stim logs --errors.",
  ]
}
