const demoEndpoint = 'wss://stim-demo.appandflow.workers.dev';

const description = [
  'Stim Mobile shows the development work running on your Mac. It is the phone companion for Stim, an open-source tool that gives each React Native or Expo workspace its own Metro port and its own simulator or emulator.',
  '',
  'This app does not compile or run your projects. It needs a Mac running Stim Desktop or stim-server, paired with this phone. Without a paired Mac there is nothing to show.',
  '',
  'WHAT YOU CAN SEE',
  '- Workspaces on every paired Mac, grouped by repository, with their state (warming, building, running, idle), error counts, pull request state and git status.',
  '- A Needs attention list: an offline Mac, low disk space, a failed build, errors in the logs, an app that is not running.',
  '- Build progress: the current step, elapsed time against the estimate, cache hit or miss with the reason, recent builds and compiler errors.',
  '- Logs from Metro, the app, iOS, Android, web, builds and coding agents, with severity and source filters, search, stack traces and code frames.',
  '- Changed and untracked files in a workspace, with their staged and unstaged diffs. This is read-only.',
  '- Mac status: CPU, memory and disk use, and what Stim could free. Cleanup itself happens on the Mac.',
  "- A notification inbox with the events your Mac's Stim server recorded.",
  '',
  'DEVICE VIEW',
  'Open a running iOS simulator, Android emulator or Stim-owned web page to watch its screen live, and scrub back through the recent footage the Mac recorded. The layout adapts to iPad and to wide or folded windows.',
  '',
  "When the Mac grants this phone Control, you can tap, type, rotate and use the device's other controls, and reload or stop a workspace. Pairings made from Stim Desktop are read-only until you allow Control for that phone on the Mac.",
  '',
  'NOTIFICATIONS',
  "Notifications are off until you turn them on. On iPhone, a Mac whose stim-server sends push notifications can reach you through Expo's push service and Apple while the app is closed. Otherwise notifications appear while the app is open.",
  '',
  'SETUP',
  "In Stim Desktop, open Pair a Phone, then scan the QR code or type the endpoint and pairing token. The camera is used only to read that code. The phone connects to your Mac over wss://. The app's own pairing prompt says the phone and the Mac both need Tailscale. The app has no accounts.",
  '',
  'REQUIREMENTS',
  'A Mac running Stim Desktop or stim-server with the stim command-line tools. Local iOS work needs Xcode and local Android work needs the Android SDK. Stim is MIT licensed, and its source is at github.com/appandflow/stim.',
].join('\n');

const reviewNotes = [
  'Stim Mobile (home-screen name: Stim) is a monitor for React Native and Expo development work. It shows workspaces, builds, logs and simulator screens that run on a Mac. The phone app does not compile or run projects. It connects to Stim Desktop or stim-server on a Mac that the user owns, so it has no content until it is paired with one. The app has no accounts and no sign-in.',
  '',
  'HOW TO REVIEW WITHOUT A MAC',
  'A demonstration server with sample data is running for review. Its address and token are in the "Demo access" lines at the end of these notes.',
  '1. Open Stim. On the first screen choose "Pair a machine". The app then asks for camera access to scan a QR code. You can decline.',
  '2. Tap "Enter the endpoint and token instead".',
  '3. Enter the endpoint (it starts with wss://) and the pairing token from the lines below, then tap "Pair". Give the machine any name.',
  'The token does not expire during review. If the app says the pairing code expired, contact us.',
  '',
  'WHAT YOU WILL SEE',
  'Home lists sample workspaces from a demo Mac, with Needs attention items. Open a workspace for its status, Build, Logs and Work cards. The Work card opens Changed files with read-only diffs. A device card opens the device viewer with the device screen (sample images, refreshed once a second). The menu opens Notifications, Devices and Machines, and About shows versions and licenses. The data is recorded sample data, not a live machine.',
  '',
  'HOW PAIRING WORKS WITH A REAL MAC',
  'Stim Desktop > Settings > Phones > turn on Serve to phones > Pair a Phone shows a QR code and an endpoint with a pairing token. The phone scans the code or takes the endpoint and token by hand. A token is single use and lasts five minutes. Pairings made this way are read-only: the phone can view workspaces, logs and device screens. The user can later allow Control for that phone on the Mac, which lets the phone tap and type on a simulator and reload or stop a workspace. The phone connects over wss://. Plain ws:// is accepted only for a loopback address on the phone itself.',
  '',
  'PERMISSIONS AND DATA',
  'Camera: used only to scan the pairing QR code, nothing is uploaded. Notifications: off until the user turns them on in Settings, and the app asks for permission at that time. On iPhone, push notifications need a Mac whose stim-server sends them through Expo and Apple; the demo server does not send push. Diagnostics: crash reports go to Sentry; the app also checks Expo Updates for app updates. The privacy policy is under About > Privacy policy in the app and in App Store Connect.',
  '',
  'OTHER NOTES',
  "The device viewer can show a web page that the user's own Mac runs; the app has no address bar and no in-app browser. Links to GitHub and other sites open in the system browser. The app contains no in-app purchases and no advertising.",
].join('\n');

function optional(entries) {
  return Object.fromEntries(entries.filter(([, value]) => value));
}

const demoToken = process.env.STIM_REVIEW_DEMO_TOKEN;

module.exports = {
  configVersion: 0,
  apple: {
    copyright: '2026 App & Flow',
    version: '1.0.0',
    categories: ['DEVELOPER_TOOLS', 'PRODUCTIVITY'],
    info: {
      'en-US': {
        title: 'Stim Mobile',
        subtitle: 'Watch React Native on a Mac',
        promoText:
          'Follow workspaces, builds, logs and simulators running on your Mac from your phone. Needs a Mac running Stim Desktop and Tailscale on both.',
        description,
        keywords: [
          'expo',
          'simulator',
          'emulator',
          'xcode',
          'gradle',
          'metro',
          'build',
          'logs',
          'worktree',
          'agent',
          'developer',
          'remote',
          'ios',
          'android',
        ],
        marketingUrl: 'https://stim.appandflow.com',
        supportUrl: 'https://stim.appandflow.com/support',
        privacyPolicyUrl: 'https://stim.appandflow.com/privacy',
      },
    },
    advisory: {
      parentalControls: false,
      ageAssurance: false,
      unrestrictedWebAccess: false,
      userGeneratedContent: false,
      messagingAndChat: false,
      advertising: false,
      profanityOrCrudeHumor: 'NONE',
      horrorOrFearThemes: 'NONE',
      alcoholTobaccoOrDrugUseOrReferences: 'NONE',
      medicalOrTreatmentInformation: 'NONE',
      healthOrWellnessTopics: false,
      matureOrSuggestiveThemes: 'NONE',
      sexualContentOrNudity: 'NONE',
      sexualContentGraphicAndNudity: 'NONE',
      violenceCartoonOrFantasy: 'NONE',
      violenceRealistic: 'NONE',
      violenceRealisticProlongedGraphicOrSadistic: 'NONE',
      gunsOrOtherWeapons: 'NONE',
      gambling: false,
      gamblingSimulated: 'NONE',
      contests: 'NONE',
      lootBox: false,
      kidsAgeBand: null,
      ageRatingOverride: 'NONE',
      koreaAgeRatingOverride: 'NONE',
    },
    review: {
      ...optional([
        ['firstName', process.env.STIM_REVIEW_FIRST_NAME],
        ['lastName', process.env.STIM_REVIEW_LAST_NAME],
        ['email', process.env.STIM_REVIEW_EMAIL],
        ['phone', process.env.STIM_REVIEW_PHONE],
      ]),
      demoRequired: false,
      notes: [
        reviewNotes,
        '',
        'Demo access',
        `Endpoint: ${demoEndpoint}`,
        ...(demoToken ? [`Pairing token: ${demoToken}`] : []),
      ].join('\n'),
    },
  },
};
