// Generated by apps/desktop/scripts/generate-tokens.mjs from apps/mobile/src/design/tokens.ts. Do not edit.

import SwiftUI

enum Space {
  static let xxs: CGFloat = 2
  static let xs: CGFloat = 4
  static let sm: CGFloat = 6
  static let md: CGFloat = 8
  static let lg: CGFloat = 12
  static let xl: CGFloat = 16
  static let xxl: CGFloat = 20
  static let xxxl: CGFloat = 24
  static let huge: CGFloat = 32
  static let giant: CGFloat = 48
}

enum Radius {
  static let small: CGFloat = 4
  static let chip: CGFloat = 7
  static let control: CGFloat = 10
  static let card: CGFloat = 12
  static let sheet: CGFloat = 20
  static let round: CGFloat = 999
}

enum Opacity {
  static let subtle: Double = 0.1
  static let pressed: Double = 0.12
  static let tint: Double = 0.16
  static let track: Double = 0.25
  static let disabled: Double = 0.4
  static let backdrop: Double = 0.9
}

enum TextVariant: CaseIterable {
  case caption2, caption, footnote, callout, body, headline, title

  var size: CGFloat {
    switch self {
    case .caption2: 10.5
    case .caption: 11
    case .footnote: 11.5
    case .callout: 12
    case .body: 13
    case .headline: 15
    case .title: 22
    }
  }

  var lineHeight: CGFloat {
    switch self {
    case .caption2: 13
    case .caption: 14
    case .footnote: 15
    case .callout: 16
    case .body: 17
    case .headline: 20
    case .title: 28
    }
  }

  var weight: Font.Weight {
    switch self {
    case .caption2: .regular
    case .caption: .regular
    case .footnote: .regular
    case .callout: .regular
    case .body: .regular
    case .headline: .semibold
    case .title: .semibold
    }
  }
}

enum Palette {
  static let primary = Color(light: 0x5521FFFF, dark: 0xB39CFFFF, lightHighContrast: 0x3C00FFFF, darkHighContrast: 0xBDA9FFFF)
  static let accent = Color(light: 0x7045FFFF, dark: 0xAA90FFFF, lightHighContrast: 0x3B01FFFF, darkHighContrast: 0xBEAAFFFF)
  static let onPrimary = Color(light: 0xFFFFFFFF, dark: 0x15121DFF, lightHighContrast: 0xFFFFFFFF, darkHighContrast: 0x15121DFF)
  static let brand = Color(light: 0x5521FFFF, dark: 0x5521FFFF, lightHighContrast: 0x5521FFFF, darkHighContrast: 0x5521FFFF)
  static let onBrand = Color(light: 0xFFFFFFFF, dark: 0xFFFFFFFF, lightHighContrast: 0xFFFFFFFF, darkHighContrast: 0xFFFFFFFF)
  static let selection = Color(light: 0xF3EFFFFF, dark: 0x2E2445FF, lightHighContrast: 0xF3EFFFFF, darkHighContrast: 0x2E2445FF)
  static let background = Color(light: 0xFFFFFFFF, dark: 0x15121DFF, lightHighContrast: 0xFFFFFFFF, darkHighContrast: 0x15121DFF)
  static let sidebar = Color(light: 0xF6F4FAFF, dark: 0x0E0C13FF, lightHighContrast: 0xF6F4FAFF, darkHighContrast: 0x0E0C13FF)
  static let surface = Color(light: 0xFCFBFFFF, dark: 0x201B2BFF, lightHighContrast: 0xFCFBFFFF, darkHighContrast: 0x201B2BFF)
  static let raised = Color(light: 0xF3EFFFFF, dark: 0x2A2338FF, lightHighContrast: 0xF3EFFFFF, darkHighContrast: 0x2A2338FF)
  static let border = Color(light: 0xECE7FAFF, dark: 0x352A48FF, lightHighContrast: 0x8C869CFF, darkHighContrast: 0x7A6F92FF)
  static let separator = Color(light: 0xECE7FAFF, dark: 0x352A48FF, lightHighContrast: 0x8C869CFF, darkHighContrast: 0x7A6F92FF)
  static let grouped = Color(light: 0xF6F4FAFF, dark: 0x0E0C13FF, lightHighContrast: 0xF6F4FAFF, darkHighContrast: 0x0E0C13FF)
  static let groupedRow = Color(light: 0xFFFFFFFF, dark: 0x201B2BFF, lightHighContrast: 0xFFFFFFFF, darkHighContrast: 0x201B2BFF)
  static let text = Color(light: 0x121212FF, dark: 0xF3EFFFFF, lightHighContrast: 0x121212FF, darkHighContrast: 0xF3EFFFFF)
  static let secondary = Color(light: 0x5F5F5FFF, dark: 0xB8B0CCFF, lightHighContrast: 0x515151FF, darkHighContrast: 0xBAB2CDFF)
  static let tertiary = Color(light: 0x706B7AFF, dark: 0x948DAAFF, lightHighContrast: 0x534F5AFF, darkHighContrast: 0xB8B3C6FF)
  static let success = Color(light: 0x0F6C31FF, dark: 0x4ADE80FF, lightHighContrast: 0x0A4921FF, darkHighContrast: 0xA2EEBEFF)
  static let warning = Color(light: 0x815516FF, dark: 0xF5B454FF, lightHighContrast: 0x57390FFF, darkHighContrast: 0xFADAABFF)
  static let error = Color(light: 0xB31D1DFF, dark: 0xFF6B6BFF, lightHighContrast: 0x7B1414FF, darkHighContrast: 0xFFD5D5FF)
  static let info = Color(light: 0x0046F2FF, dark: 0x7AA7FFFF, lightHighContrast: 0x0030A5FF, darkHighContrast: 0xD1E0FFFF)
  static let shadow = Color(light: 0x000000FF, dark: 0x000000FF, lightHighContrast: 0x000000FF, darkHighContrast: 0x000000FF)
  static let scrim = Color(light: 0x00000024, dark: 0x00000024, lightHighContrast: 0x00000024, darkHighContrast: 0x00000024)

  static let all: [(name: String, color: Color)] = [
    ("primary", primary),
    ("accent", accent),
    ("onPrimary", onPrimary),
    ("brand", brand),
    ("onBrand", onBrand),
    ("selection", selection),
    ("background", background),
    ("sidebar", sidebar),
    ("surface", surface),
    ("raised", raised),
    ("border", border),
    ("separator", separator),
    ("grouped", grouped),
    ("groupedRow", groupedRow),
    ("text", text),
    ("secondary", secondary),
    ("tertiary", tertiary),
    ("success", success),
    ("warning", warning),
    ("error", error),
    ("info", info),
    ("shadow", shadow),
    ("scrim", scrim),
  ]
}

enum Media {
  static let screen = Color(rgba: 0x0C0A11FF)
  static let frame = Color(rgba: 0x000000FF)
  static let text = Color(rgba: 0xFFFFFFFF)
  static let textSecondary = Color(rgba: 0xFFFFFFCC)
  static let textTertiary = Color(rgba: 0xFFFFFF99)
  static let fill = Color(rgba: 0xFFFFFF1F)
  static let fillSubtle = Color(rgba: 0xFFFFFF14)
  static let bar = Color(rgba: 0x1C1C1EFF)
  static let note = Color(rgba: 0x000000D9)
  static let badge = Color(rgba: 0x00000099)
}

enum FontFamily {
  static let sans = "InterVariable"
  static let mono = "JetBrainsMono-Regular"
}
