// Generated by apps/desktop/scripts/generate-tokens.mjs from apps/mobile/src/design/tokens.ts. Do not edit.

import SwiftUI

enum Space {
  static let xxs: CGFloat = 2
  static let xs: CGFloat = 4
  static let sm: CGFloat = 6
  static let md: CGFloat = 8
  static let lg: CGFloat = 12
  static let xl: CGFloat = 16
  static let xxl: CGFloat = 20
  static let xxxl: CGFloat = 24
  static let huge: CGFloat = 32
}

enum Radius {
  static let small: CGFloat = 4
  static let chip: CGFloat = 7
  static let control: CGFloat = 10
  static let card: CGFloat = 12
  static let sheet: CGFloat = 20
  static let round: CGFloat = 999
}

enum Opacity {
  static let subtle: Double = 0.1
  static let pressed: Double = 0.12
  static let tint: Double = 0.16
  static let track: Double = 0.25
  static let disabled: Double = 0.4
  static let backdrop: Double = 0.9
}

enum TextVariant: CaseIterable {
  case caption2, caption, footnote, callout, body, headline, title

  var size: CGFloat {
    switch self {
    case .caption2: 10.5
    case .caption: 11
    case .footnote: 11.5
    case .callout: 12
    case .body: 13
    case .headline: 15
    case .title: 22
    }
  }

  var lineHeight: CGFloat {
    switch self {
    case .caption2: 13
    case .caption: 14
    case .footnote: 15
    case .callout: 16
    case .body: 17
    case .headline: 20
    case .title: 28
    }
  }

  var weight: Font.Weight {
    switch self {
    case .caption2: .regular
    case .caption: .regular
    case .footnote: .regular
    case .callout: .regular
    case .body: .regular
    case .headline: .semibold
    case .title: .semibold
    }
  }
}

enum Palette {
  static let primary = Color(light: 0x5521FFFF, dark: 0xB39CFFFF)
  static let accent = Color(light: 0x7045FFFF, dark: 0xAA90FFFF)
  static let onPrimary = Color(light: 0xFFFFFFFF, dark: 0x15121DFF)
  static let brand = Color(light: 0x5521FFFF, dark: 0x5521FFFF)
  static let onBrand = Color(light: 0xFFFFFFFF, dark: 0xFFFFFFFF)
  static let selection = Color(light: 0xF3EFFFFF, dark: 0x2E2445FF)
  static let background = Color(light: 0xFFFFFFFF, dark: 0x15121DFF)
  static let sidebar = Color(light: 0xF6F4FAFF, dark: 0x0E0C13FF)
  static let surface = Color(light: 0xFCFBFFFF, dark: 0x201B2BFF)
  static let raised = Color(light: 0xF3EFFFFF, dark: 0x2A2338FF)
  static let border = Color(light: 0xECE7FAFF, dark: 0x352A48FF)
  static let separator = Color(light: 0xECE7FAFF, dark: 0x352A48FF)
  static let grouped = Color(light: 0xF6F4FAFF, dark: 0x0E0C13FF)
  static let groupedRow = Color(light: 0xFFFFFFFF, dark: 0x201B2BFF)
  static let text = Color(light: 0x121212FF, dark: 0xF3EFFFFF)
  static let secondary = Color(light: 0x6B6B6BFF, dark: 0xB8B0CCFF)
  static let tertiary = Color(light: 0x96929FFF, dark: 0x8C84A3FF)
  static let success = Color(light: 0x16A34AFF, dark: 0x4ADE80FF)
  static let warning = Color(light: 0xB7791FFF, dark: 0xF5B454FF)
  static let error = Color(light: 0xDC2626FF, dark: 0xFF6B6BFF)
  static let info = Color(light: 0x2F6BFFFF, dark: 0x7AA7FFFF)
  static let shadow = Color(light: 0x000000FF, dark: 0x000000FF)
  static let scrim = Color(light: 0x00000024, dark: 0x00000024)

  static let all: [(name: String, color: Color)] = [
    ("primary", primary),
    ("accent", accent),
    ("onPrimary", onPrimary),
    ("brand", brand),
    ("onBrand", onBrand),
    ("selection", selection),
    ("background", background),
    ("sidebar", sidebar),
    ("surface", surface),
    ("raised", raised),
    ("border", border),
    ("separator", separator),
    ("grouped", grouped),
    ("groupedRow", groupedRow),
    ("text", text),
    ("secondary", secondary),
    ("tertiary", tertiary),
    ("success", success),
    ("warning", warning),
    ("error", error),
    ("info", info),
    ("shadow", shadow),
    ("scrim", scrim),
  ]
}

enum Media {
  static let screen = Color(rgba: 0x0C0A11FF)
  static let frame = Color(rgba: 0x000000FF)
  static let text = Color(rgba: 0xFFFFFFFF)
  static let textSecondary = Color(rgba: 0xFFFFFFCC)
  static let textTertiary = Color(rgba: 0xFFFFFF99)
  static let fill = Color(rgba: 0xFFFFFF1F)
  static let fillSubtle = Color(rgba: 0xFFFFFF14)
  static let bar = Color(rgba: 0x1C1C1EFF)
  static let note = Color(rgba: 0x000000D9)
  static let badge = Color(rgba: 0x00000099)
}

enum FontFamily {
  static let sans = "InterVariable"
  static let mono = "JetBrainsMono-Regular"
}
