// These rows are RELEASE.md section 3. Editing that table without editing this
// file leaves the release owner choosing a matrix the script cannot reproduce.
export const qaRows = [
  {
    id: 'loop',
    change: 'Command lifecycle, worktrees, devices, or framework detection',
    evidence: '`loop` for each affected framework/platform',
    axis: 'framework+platform',
    absent: 'no changed path touches command lifecycle, worktrees, devices, or framework detection',
  },
  {
    id: 'logs',
    change: 'Log collection, error queries, or timeline behavior',
    evidence: 'field protocol logs row on each affected platform',
    axis: 'platform',
    absent: 'no changed path touches log collection, error queries, or timeline behavior',
  },
  {
    id: 'caches',
    change: 'Build, cache, fingerprint, Pods, Metro, single-flight, or `gc` behavior',
    evidence: '`caches` for each affected platform and each affected Metro mode',
    axis: 'platform',
    absent: 'no changed path touches build, cache, fingerprint, Pods, Metro, single-flight, or gc behavior',
  },
  {
    id: 'real-repository',
    change: 'Project detection, prebuild, monorepo, or hoisted-dependency behavior',
    evidence: 'field protocol on a representative real repository',
    axis: 'global',
    absent: 'no changed path touches project detection, prebuild, monorepo, or hoisted-dependency behavior',
  },
  {
    id: 'remote-provider',
    change: 'Remote device, tunnel, or remote build-cache behavior',
    evidence: 'field protocol with the affected authenticated provider',
    axis: 'global',
    absent: 'no changed path touches remote device, tunnel, or remote build-cache behavior',
  },
  {
    id: 'release-build',
    change: 'Release build or JS/APK swap behavior',
    evidence: 'field protocol release row on each affected platform',
    axis: 'platform',
    absent: 'no changed path touches release build or JS/APK swap behavior',
  },
  {
    id: 'android-flavor',
    change: 'Android variant or artifact selection',
    evidence: 'field protocol on a real flavored Android repository',
    axis: 'global',
    absent: 'no changed path touches Android variant or artifact selection',
  },
  {
    id: 'launch-evidence',
    change: 'Launch status, remedies, or interaction UX',
    evidence: 'field protocol launch-evidence row on each affected platform',
    axis: 'platform',
    absent: 'no changed path touches launch status, remedies, or interaction UX',
  },
];

const everyRow = qaRows.map((row) => row.id);
const ios = ['ios'];
const android = ['android'];

export const pathRules = [
  { path: 'packages/core', rows: ['caches', 'loop'] },
  { path: 'packages/cache', rows: ['caches', 'remote-provider'] },
  { path: 'packages/metro', rows: ['caches', 'logs'] },
  { path: 'packages/expo-build-cache', rows: ['caches'] },

  { path: 'packages/stim-cli', rows: ['loop'] },
  { path: 'packages/stim-cli/bin', rows: ['loop'] },
  { path: 'packages/stim-cli/shim', rows: ['loop', 'caches'] },
  { path: 'packages/stim-cli/README.md', exempt: 'documentation' },
  { path: 'packages/stim-cli/skill', exempt: 'static skill router, covered by guide contract tests' },

  { path: 'packages/stim-cli/src', rows: everyRow },
  { path: 'packages/stim-cli/src/__tests__', exempt: 'unit tests, run by the section 2 preflight' },
  { path: 'packages/stim-cli/src/guide', exempt: 'agent guidance text, covered by guide contract tests' },

  { path: 'packages/stim-cli/src/agent-device-cleanup.ts', rows: ['loop'] },
  { path: 'packages/stim-cli/src/command-output.ts', rows: ['loop', 'launch-evidence'] },
  { path: 'packages/stim-cli/src/config.ts', rows: ['loop', 'caches'] },
  { path: 'packages/stim-cli/src/avd-claim.ts', rows: ['loop'], platforms: android },
  { path: 'packages/stim-cli/src/build-cache.ts', rows: ['caches'] },
  { path: 'packages/stim-cli/src/cache-manifest.ts', rows: ['caches'] },
  { path: 'packages/stim-cli/src/caches.ts', rows: ['caches'] },
  { path: 'packages/stim-cli/src/dependency-state.ts', rows: ['caches', 'real-repository'] },
  { path: 'packages/stim-cli/src/device-slots.ts', rows: ['loop'] },
  { path: 'packages/stim-cli/src/diagnostic-store.ts', rows: ['logs'] },
  { path: 'packages/stim-cli/src/dir-lock.ts', rows: ['loop', 'caches'] },
  { path: 'packages/stim-cli/src/doctor.ts', rows: ['loop', 'caches'] },
  { path: 'packages/stim-cli/src/doctor-config.ts', rows: ['loop', 'caches'] },
  { path: 'packages/stim-cli/src/doctor-cxx.ts', rows: ['loop', 'caches'] },
  { path: 'packages/stim-cli/src/doctor-ios-architectures.ts', rows: ['loop', 'caches'], platforms: ios },
  { path: 'packages/stim-cli/src/doctor-storage.ts', rows: ['loop', 'caches'] },
  { path: 'packages/stim-cli/src/error-diagnostics.ts', rows: ['logs'] },
  { path: 'packages/stim-cli/src/error-symbolication.ts', rows: ['logs'] },
  { path: 'packages/stim-cli/src/guide-status.ts', rows: ['loop'] },
  { path: 'packages/stim-cli/src/host-memory.ts', rows: ['loop', 'caches'] },
  { path: 'packages/stim-cli/src/launch-error-preview.ts', rows: ['logs', 'launch-evidence'] },
  { path: 'packages/stim-cli/src/logs-query.ts', rows: ['logs'] },
  { path: 'packages/stim-cli/src/metro.ts', rows: ['caches', 'loop'] },
  { path: 'packages/stim-cli/src/named-ports.ts', rows: ['loop'] },
  { path: 'packages/stim-cli/src/native-crash.ts', rows: ['logs', 'launch-evidence'] },
  { path: 'packages/stim-cli/src/ndjson.ts', rows: ['logs'] },
  { path: 'packages/stim-cli/src/optimizations.ts', rows: ['caches'] },
  { path: 'packages/stim-cli/src/ownership-claim.ts', rows: ['loop', 'caches'] },
  { path: 'packages/stim-cli/src/paths.ts', rows: ['loop', 'caches'] },
  { path: 'packages/stim-cli/src/ports.ts', rows: ['loop'] },
  { path: 'packages/stim-cli/src/process-identity.ts', rows: ['loop', 'caches'] },
  { path: 'packages/stim-cli/src/process-output.ts', rows: ['logs'] },
  { path: 'packages/stim-cli/src/project.ts', rows: ['real-repository', 'loop'] },
  { path: 'packages/stim-cli/src/reclaim.ts', rows: ['loop', 'caches'] },
  { path: 'packages/stim-cli/src/sandbox.ts', rows: ['loop', 'caches'] },
  { path: 'packages/stim-cli/src/settings.ts', rows: ['loop', 'caches', 'remote-provider'] },
  { path: 'packages/stim-cli/src/sim-pool.ts', rows: ['loop'] },
  { path: 'packages/stim-cli/src/spawn-entry.ts', rows: ['loop'] },
  { path: 'packages/stim-cli/src/status.ts', rows: ['loop'] },
  { path: 'packages/stim-cli/src/stim-installations.ts', rows: ['loop'] },
  { path: 'packages/stim-cli/src/teardown.ts', rows: ['loop'] },
  { path: 'packages/stim-cli/src/temporary.ts', rows: ['loop', 'caches'] },
  { path: 'packages/stim-cli/src/workspace-state.ts', rows: ['loop'] },
  { path: 'packages/stim-cli/src/worktree.ts', rows: ['loop', 'caches'] },
  { path: 'packages/stim-cli/src/worktree-refresh.ts', rows: ['loop', 'caches'] },

  { path: 'packages/stim-cli/src/collector', rows: everyRow },
  { path: 'packages/stim-cli/src/collector/android.ts', rows: ['logs'], platforms: android },
  { path: 'packages/stim-cli/src/collector/ios.ts', rows: ['logs'], platforms: ios },
  { path: 'packages/stim-cli/src/collector/ios-device.ts', rows: ['logs'], platforms: ios },
  { path: 'packages/stim-cli/src/collector/ownership.ts', rows: ['logs', 'loop'] },
  { path: 'packages/stim-cli/src/collector/run.ts', rows: ['logs', 'loop'] },
  { path: 'packages/stim-cli/src/collector/state.ts', rows: ['logs', 'loop'] },

  { path: 'packages/stim-cli/src/sim', rows: everyRow },
  { path: 'packages/stim-cli/src/sim/android.ts', rows: ['loop'], platforms: android },
  { path: 'packages/stim-cli/src/sim/ios.ts', rows: ['loop'], platforms: ios },

  { path: 'packages/stim-cli/src/supervisor', rows: everyRow },
  { path: 'packages/stim-cli/src/supervisor/cache-reset.ts', rows: ['caches'] },
  { path: 'packages/stim-cli/src/supervisor/errors.ts', rows: ['logs'] },
  { path: 'packages/stim-cli/src/supervisor/metro-store.ts', rows: ['caches'] },
  { path: 'packages/stim-cli/src/supervisor/ownership.ts', rows: ['loop'] },
  { path: 'packages/stim-cli/src/supervisor/run.ts', rows: ['loop', 'caches'] },
  { path: 'packages/stim-cli/src/supervisor/server-bare.ts', rows: ['loop', 'caches'], frameworks: ['bare'] },
  { path: 'packages/stim-cli/src/supervisor/server-expo.ts', rows: ['loop', 'caches'], frameworks: ['expo'] },
  { path: 'packages/stim-cli/src/supervisor/state.ts', rows: ['loop'] },

  { path: 'packages/stim-cli/src/commands', rows: everyRow },
  { path: 'packages/stim-cli/src/commands/dev-client.ts', rows: ['loop', 'launch-evidence'] },
  { path: 'packages/stim-cli/src/commands/device.ts', rows: ['loop'] },
  { path: 'packages/stim-cli/src/commands/doctor.ts', rows: ['loop', 'caches'] },
  { path: 'packages/stim-cli/src/commands/guide.ts', exempt: 'agent guidance text, covered by guide contract tests' },
  { path: 'packages/stim-cli/src/commands/logs.ts', rows: ['logs'] },
  { path: 'packages/stim-cli/src/commands/native-runtime.ts', rows: ['loop', 'caches', 'launch-evidence'] },
  { path: 'packages/stim-cli/src/commands/ports.ts', rows: ['loop'] },
  { path: 'packages/stim-cli/src/commands/reload.ts', rows: ['loop', 'launch-evidence'] },
  { path: 'packages/stim-cli/src/commands/start.ts', rows: ['loop', 'caches'] },
  { path: 'packages/stim-cli/src/commands/stats.ts', rows: ['loop'] },
  { path: 'packages/stim-cli/src/commands/status.ts', rows: ['loop'] },
  { path: 'packages/stim-cli/src/commands/stop.ts', rows: ['loop'] },
  { path: 'packages/stim-cli/src/commands/worktree.ts', rows: ['loop', 'caches'] },

  { path: 'packages/stim-cli/src/commands/gc', rows: everyRow },
  { path: 'packages/stim-cli/src/commands/gc.ts', rows: ['caches', 'loop'] },
  { path: 'packages/stim-cli/src/commands/gc/caches.ts', rows: ['caches'] },
  { path: 'packages/stim-cli/src/commands/gc/devices.ts', rows: ['loop'] },
  { path: 'packages/stim-cli/src/commands/gc/eas-sessions.ts', rows: ['remote-provider'] },
  { path: 'packages/stim-cli/src/commands/gc/paths.ts', rows: ['caches', 'loop'] },
  { path: 'packages/stim-cli/src/commands/gc/report.ts', rows: ['caches', 'loop'] },

  { path: 'packages/stim-cli/src/commands/ios', rows: everyRow, platforms: ios },
  {
    path: 'packages/stim-cli/src/commands/ios.ts',
    rows: ['loop', 'caches', 'launch-evidence', 'release-build'],
    platforms: ios,
  },
  { path: 'packages/stim-cli/src/commands/ios/artifact.ts', rows: ['caches', 'release-build'], platforms: ios },
  { path: 'packages/stim-cli/src/commands/ios/collector.ts', rows: ['logs'], platforms: ios },
  { path: 'packages/stim-cli/src/commands/ios/launch.ts', rows: ['loop', 'launch-evidence'], platforms: ios },
  {
    path: 'packages/stim-cli/src/commands/ios/result.ts',
    rows: ['loop', 'caches', 'launch-evidence'],
    platforms: ios,
  },
  { path: 'packages/stim-cli/src/commands/ios/support.ts', rows: ['loop'], platforms: ios },
  {
    path: 'packages/stim-cli/src/commands/ios/dependencies.ts',
    rows: ['loop', 'caches', 'launch-evidence', 'release-build'],
    platforms: ios,
  },
  {
    path: 'packages/stim-cli/src/commands/ios/types.ts',
    rows: ['loop', 'caches', 'launch-evidence', 'release-build'],
    platforms: ios,
  },

  { path: 'packages/stim-cli/src/commands/android', rows: everyRow, platforms: android },
  {
    path: 'packages/stim-cli/src/commands/android.ts',
    rows: ['loop', 'caches', 'launch-evidence', 'release-build', 'android-flavor'],
    platforms: android,
  },
  { path: 'packages/stim-cli/src/commands/android/collector.ts', rows: ['logs'], platforms: android },
  { path: 'packages/stim-cli/src/commands/android/launch.ts', rows: ['loop', 'launch-evidence'], platforms: android },
  {
    path: 'packages/stim-cli/src/commands/android/plan.ts',
    rows: ['loop', 'caches', 'release-build', 'android-flavor'],
    platforms: android,
  },
  {
    path: 'packages/stim-cli/src/commands/android/result.ts',
    rows: ['loop', 'caches', 'launch-evidence'],
    platforms: android,
  },
  {
    path: 'packages/stim-cli/src/commands/android/support.ts',
    rows: ['loop', 'android-flavor'],
    platforms: android,
  },

  {
    path: 'packages/stim-cli/src/commands/android/types.ts',
    rows: ['loop', 'caches', 'launch-evidence', 'release-build', 'android-flavor'],
    platforms: android,
  },

  { path: 'packages/stim-cli/src/engine', rows: everyRow },
  { path: 'packages/stim-cli/src/engine/agent-device.ts', rows: ['loop', 'launch-evidence'] },
  { path: 'packages/stim-cli/src/engine/android-avd-setup.ts', rows: ['loop'], platforms: android },
  { path: 'packages/stim-cli/src/engine/android-cas.ts', rows: ['caches'], platforms: android },
  {
    path: 'packages/stim-cli/src/engine/apk-swap.ts',
    rows: ['release-build', 'android-flavor'],
    platforms: android,
  },
  { path: 'packages/stim-cli/src/engine/app-install.ts', rows: ['loop', 'launch-evidence'] },
  { path: 'packages/stim-cli/src/engine/app-readiness.ts', rows: ['loop', 'launch-evidence'] },
  { path: 'packages/stim-cli/src/engine/asset-manifest.ts', rows: ['release-build'], platforms: android },
  { path: 'packages/stim-cli/src/engine/build-lock.ts', rows: ['loop', 'caches'] },
  { path: 'packages/stim-cli/src/engine/build-slots.ts', rows: ['loop', 'caches'] },
  { path: 'packages/stim-cli/src/engine/bundler.ts', rows: ['release-build', 'caches'] },
  { path: 'packages/stim-cli/src/engine/ccache.ts', rows: ['caches'], platforms: ios },
  { path: 'packages/stim-cli/src/engine/deps.ts', rows: ['real-repository', 'caches'] },
  { path: 'packages/stim-cli/src/engine/device.ts', rows: ['loop', 'launch-evidence'] },
  { path: 'packages/stim-cli/src/engine/device-lease.ts', rows: ['loop'] },
  { path: 'packages/stim-cli/src/engine/device-lease-run.ts', rows: ['loop'] },
  { path: 'packages/stim-cli/src/engine/device-pool.ts', rows: ['loop'] },
  { path: 'packages/stim-cli/src/engine/device-remote.ts', rows: ['remote-provider'] },
  { path: 'packages/stim-cli/src/engine/eas-build.ts', rows: ['remote-provider', 'caches'] },
  { path: 'packages/stim-cli/src/engine/eas-project-lock.ts', rows: ['remote-provider'] },
  { path: 'packages/stim-cli/src/engine/eas-session-ledger.ts', rows: ['remote-provider'] },
  { path: 'packages/stim-cli/src/engine/eas-simulator.ts', rows: ['remote-provider'] },
  { path: 'packages/stim-cli/src/engine/errors-gradle.ts', rows: ['logs'], platforms: android },
  { path: 'packages/stim-cli/src/engine/errors-xcode.ts', rows: ['logs'], platforms: ios },
  { path: 'packages/stim-cli/src/engine/gradle.ts', rows: ['caches', 'loop'], platforms: android },
  {
    path: 'packages/stim-cli/src/engine/installed-artifact.ts',
    rows: ['caches', 'release-build', 'android-flavor'],
  },
  { path: 'packages/stim-cli/src/engine/ios-device.ts', rows: ['loop', 'launch-evidence'], platforms: ios },
  { path: 'packages/stim-cli/src/engine/ios-lan.ts', rows: ['remote-provider'], platforms: ios },
  { path: 'packages/stim-cli/src/engine/ios-profile.ts', rows: ['loop'], platforms: ios },
  { path: 'packages/stim-cli/src/engine/ios-signing.ts', rows: ['loop'], platforms: ios },
  { path: 'packages/stim-cli/src/engine/js-swap.ts', rows: ['release-build'] },
  { path: 'packages/stim-cli/src/engine/lan-address.ts', rows: ['remote-provider'] },
  { path: 'packages/stim-cli/src/engine/metro-gate.ts', rows: ['loop', 'caches', 'launch-evidence'] },
  { path: 'packages/stim-cli/src/engine/metro-reach.ts', rows: ['launch-evidence', 'remote-provider'] },
  { path: 'packages/stim-cli/src/engine/metro-warmup.ts', rows: ['caches'] },
  { path: 'packages/stim-cli/src/engine/prebuild.ts', rows: ['real-repository', 'caches'] },
  { path: 'packages/stim-cli/src/engine/reload.ts', rows: ['loop', 'launch-evidence'] },
  { path: 'packages/stim-cli/src/engine/remote-cache.ts', rows: ['remote-provider', 'caches'] },
  { path: 'packages/stim-cli/src/engine/simslim.ts', rows: ['caches'], platforms: ios },
  { path: 'packages/stim-cli/src/engine/slot-launch.ts', rows: ['loop', 'launch-evidence'] },
  { path: 'packages/stim-cli/src/engine/stats.ts', rows: ['loop'] },
  { path: 'packages/stim-cli/src/engine/tunnel.ts', rows: ['remote-provider'] },
  { path: 'packages/stim-cli/src/engine/warm-claim.ts', rows: ['loop', 'caches'] },
  { path: 'packages/stim-cli/src/engine/workspace-process-lock.ts', rows: ['loop'] },
  { path: 'packages/stim-cli/src/engine/xcode.ts', rows: ['caches', 'loop'], platforms: ios },

  { path: 'pnpm-lock.yaml', rows: ['loop', 'caches'] },

  { path: 'test', exempt: 'tests, run by the section 2 preflight' },
  { path: 'test/e2e/native', rows: ['loop', 'caches'] },
  { path: 'test/e2e/native/assertions.mjs', rows: ['loop', 'caches'] },
  { path: 'test/e2e/native/gradle-home.mjs', rows: ['caches'], platforms: android },
  { path: 'test/e2e/native/harness.mjs', rows: ['loop', 'caches'] },
  { path: 'test/e2e/native/monitor-macos-memory.mjs', rows: ['loop', 'caches'] },
  { path: 'test/e2e/native/prepare-ios-device.mjs', rows: ['loop'], platforms: ios },
  { path: 'test/e2e/native/run-android-pool-e2e.mjs', rows: ['loop'], platforms: android },
  { path: 'test/e2e/native/run-cache-e2e.mjs', rows: ['caches'] },
  { path: 'test/e2e/native/run-native-e2e.mjs', rows: ['loop'] },
  { path: 'test/e2e/native/run-pool-e2e.mjs', rows: ['loop'] },
  { path: 'test/e2e/native/simslim-profile.json', rows: ['caches'], platforms: ios },

  { path: 'docs', exempt: 'documentation' },
  { path: 'website', exempt: 'documentation website' },
  { path: 'scripts', exempt: 'repository tooling, not published behavior' },
  { path: '.claude', exempt: 'local agent configuration, not published behavior' },
  { path: '.github', exempt: 'CI configuration, covered by the exact-commit CI in section 4' },
  { path: '.gitignore', exempt: 'repository tooling, not published behavior' },
  { path: '.nvmrc', exempt: 'repository tooling, not published behavior' },
  { path: '.oxfmtrc.json', exempt: 'repository tooling, not published behavior' },
  { path: '.oxlintrc.json', exempt: 'repository tooling, not published behavior' },
  { path: 'AGENTS.md', exempt: 'documentation' },
  { path: 'CLAUDE.md', exempt: 'documentation' },
  { path: 'README.md', exempt: 'documentation' },
  { path: 'RELEASE.md', exempt: 'documentation' },
  { path: 'LICENSE', exempt: 'license' },
  { path: 'knip.json', exempt: 'repository tooling, not published behavior' },
  { path: 'package.json', exempt: 'workspace root manifest, not published' },
  { path: 'pnpm-workspace.yaml', exempt: 'workspace layout, not published behavior' },
  { path: 'tsconfig.json', exempt: 'type-check configuration, covered by typecheck' },
  { path: 'tsconfig.base.json', exempt: 'type-check configuration, covered by typecheck' },
  { path: 'vitest.config.ts', exempt: 'test configuration, covered by the unit suite' },
  { path: 'vitest.compat.config.ts', exempt: 'test configuration, covered by the unit suite' },
  { path: 'vitest.setup.ts', exempt: 'test configuration, covered by the unit suite' },
];

export const defaultMapping = { rows: qaRows, rules: pathRules };
